os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: docker

addons:
  apt:
    packages:
    - sshpass

script:
- docker-compose build
- docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
- docker push otakushelter/profile:1.0.$TRAVIS_BUILD_NUMBER

deploy:
  skip_cleanup: true
  provider: script
  script: deploy.sh