database:
  host: database.otaku-shelter.ru
  port: 5432
  database: profile
  userid: profile
  migrationstable: migrations

roles:
  admin: admin
  user: user

issuer: otakushelter.issuer
audience: otakushelter.audience