database:
  host: database.otaku-shelter.ru
  port: 5432
  database: profile
  userid: profile
  migrationstable: migrations
  
secret: secretsecretsecretsecretsecret
issuer: otakushelter.issuer
audience: otakushelter.audience