database:
  host: database.otaku-shelter.ru
  port: 5432
  database: profile
  userid: profile
  migrationstable: migrations

rabbitmq:
  instancename: profiles
  username: otakushelter
  port: 5672
  virtualhost: /
  hostname: rabbitmq.otaku-shelter.ru

roles:
  admin: admin
  user: user

issuer: account.otaku-shelter.ru
audience: otaku-shelter.ru